"""empty message

Revision ID: faa1bab40eb3
Revises: cf84afa45dcb
Create Date: 2018-12-19 23:29:11.738557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa1bab40eb3'
down_revision = 'cf84afa45dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feature', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feature', type_='foreignkey')
    op.drop_column('feature', 'product_id')
    # ### end Alembic commands ###
